# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam's Stats Inn
email: basedora@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Sam-CHChiu.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  Sam-CHChiu

# Build settings
markdown: kramdown

# Comment provided by staticman
comments:
 provider: "staticman"
   staticman:
 allowedFields          : ['name', 'email', 'url', 'message']
 branch                 : # "master", "gh-pages"
 commitMessage          : "New comment."
 filename               : comment-{@timestamp}
 format                 : "yml"
 moderation             : false
 path                   : "_data/comments/{options.slug}"
 requiredFields         : ['name', 'email', 'message']
 transforms:
   email                : "md5"
 generatedFields:
   date:
type               : "date"
options:
  format           : "iso8601"
